repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(src|tests|examples)/
      - id: ruff-format
        files: ^(src|tests|examples)/
