"""Storage abstraction layer for the control plane."""

from agent_control_plane.storage.protocols import (
    ApprovalRepository,
    AsyncApprovalRepository,
    AsyncCommandRepository,
    AsyncEventRepository,
    AsyncProposalRepository,
    AsyncSessionRepository,
    AsyncTokenBudgetRepository,
    AsyncUnitOfWork,
    CommandRepository,
    EventRepository,
    ProposalRepository,
    SessionRepository,
    SyncUnitOfWork,
    TokenBudgetRepository,
)
from agent_control_plane.storage.sqlalchemy_async import (
    AsyncSqlAlchemyApprovalRepo,
    AsyncSqlAlchemyCommandRepo,
    AsyncSqlAlchemyEventRepo,
    AsyncSqlAlchemyProposalRepo,
    AsyncSqlAlchemySessionRepo,
    AsyncSqlAlchemyUnitOfWork,
)
from agent_control_plane.storage.sqlalchemy_sync import (
    SyncSqlAlchemyApprovalRepo,
    SyncSqlAlchemyCommandRepo,
    SyncSqlAlchemyEventRepo,
    SyncSqlAlchemyProposalRepo,
    SyncSqlAlchemySessionRepo,
    SyncSqlAlchemyUnitOfWork,
)

__all__ = [
    "ApprovalRepository",
    "AsyncApprovalRepository",
    "AsyncCommandRepository",
    "AsyncEventRepository",
    "AsyncProposalRepository",
    "AsyncSessionRepository",
    "AsyncSqlAlchemyApprovalRepo",
    "AsyncSqlAlchemyCommandRepo",
    "AsyncSqlAlchemyEventRepo",
    "AsyncSqlAlchemyProposalRepo",
    "AsyncSqlAlchemySessionRepo",
    "AsyncSqlAlchemyUnitOfWork",
    "AsyncTokenBudgetRepository",
    "AsyncUnitOfWork",
    "CommandRepository",
    "EventRepository",
    "ProposalRepository",
    "SessionRepository",
    "SyncSqlAlchemyApprovalRepo",
    "SyncSqlAlchemyCommandRepo",
    "SyncSqlAlchemyEventRepo",
    "SyncSqlAlchemyProposalRepo",
    "SyncSqlAlchemySessionRepo",
    "SyncSqlAlchemyUnitOfWork",
    "SyncUnitOfWork",
    "TokenBudgetRepository",
]
